ee_tests/Dockerfile.builder
ee_tests/cico_build_deploy.sh
ee_tests/cico_run_EE_tests.sh

Do not merge yet...
I reworked Dockerfile a bit and split build and test run into 2 scripts. I'll setup jobs appropriately

[WIP] Rework Dockerfile and build scripts

---

.gitignore
ee_tests/README.md
ee_tests/local_run_EE_fabric8_test.sh
ee_tests/local_run_EE_tests.sh
ee_tests/protractorEE-fabric8.config.js
ee_tests/src/tests/work-item/work-item-list/EE/openshift-io-burr-quickstart.spec.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-F8-OS-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-F8-keycloak-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-RHD-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-gettingstarted.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-github-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-openshift-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-start.page.js
ee_tests/src/tests/work-item/work-item-list/testSupport.js

lets use more parameters to handle how to login with different platforms to
OSIO such as local fabric8 installs on minishift also add the new fabric8
pages used during the login process also allow a parameter to define which
quickstarts to test

refactor to reuse E2E tests on openshift.io and fabric8

---

ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-F8-OS-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-dashboard.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-gettingstarted.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-github-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-start.page.js
ee_tests/src/tests/work-item/work-item-list/testSupport.js

and get E2E tests to work with fabric8 on kubernetes too

polish tests

---

EE_API_automation/pyresttest/.bash_history
EE_API_automation/pyresttest/API_link_workitems.yaml
EE_API_automation/pyresttest/API_search_api.yaml
EE_API_automation/pyresttest/POST/setup/add_wi_comment1.json
EE_API_automation/pyresttest/POST/setup/add_wi_comment2.json
EE_API_automation/pyresttest/POST/setup/create_nested_iteration1a.json
EE_API_automation/pyresttest/POST/setup/create_nested_iteration1b.json
EE_API_automation/pyresttest/POST/setup/create_nested_iteration2a.json
EE_API_automation/pyresttest/POST/setup/create_nested_iteration2b.json
EE_API_automation/pyresttest/POST/setup/create_wi11_17_hierarchy.json
EE_API_automation/pyresttest/POST/setup/create_wi13_15_hierarchy.json
EE_API_automation/pyresttest/POST/setup/create_wi17_19_hierarchy.json
EE_API_automation/pyresttest/POST/setup/create_wi5_11_hierarchy.json
EE_API_automation/pyresttest/POST/setup/create_wi7_13_hierarchy.json
EE_API_automation/pyresttest/POST/setup/create_wi_scenario.json
EE_API_automation/pyresttest/UI_automation_test_setup.yaml
EE_API_automation/pyresttest/_test_add_nested_iterations.yaml
EE_API_automation/pyresttest/_test_add_workitem_comments.yaml
EE_API_automation/pyresttest/_test_create_workitem_hierarchies.yaml
EE_API_automation/pyresttest/_test_setup_create_space_areas_iterations.yaml
EE_API_automation/pyresttest/_test_setup_create_workitems.yaml

fix(test):updated test database

---

ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-F8-OS-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-dashboard.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-gettingstarted.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-github-login.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-spacehome.page.js
ee_tests/src/tests/work-item/work-item-list/testSupport.js

polish tests for minikube + GKE

---

README.md
ee_tests/protractorEE-env.config.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-profile-tenant.page.js
ee_tests/src/tests/work-item/work-item-list/page-objects/openshift-io-spacehome.page.js
ee_tests/src/tests/work-item/work-item-list/testSupport.js

lets parameterise the E2E tests so we can use them to test PRs of new
boosters or PRs of new tenant YAMLs

support custom boosters / tenant YAMLs in tests

---

EE_API_automation/pyresttest/_test_setup_create_space_areas_iterations.yaml

This PR fixes newly introduced API redirection to auth. Failing tests have been fixed.

fix(test): handle newly added api redirections

---

ee_tests/src/specs/page_objects/login.page.ts
ee_tests/src/specs/planner-simple-create.spec.ts
ee_tests/src/specs/support/interactions.ts

See: https://github.com/openshiftio/openshift.io/issues/1402

Remove Login workaround as issue 1402 is fixed

---

EE_API_automation/pytest/src/support/constants.py
EE_API_automation/pytest/src/support/post_jsons/enable_experimental.json
EE_API_automation/pytest/src/test_planner.py

This PR sets the 'Enable experimental features' flag in the user profile on OSIO.

fix(test):enable experimental features

---

ee_tests/src/specs/quickstart_pipeline.spec.ts

The errors were swallowed and not propagated. As a result, Protractor
marked the test as passed instead of failed.

fix(test): Fixed error handling

---

ee_tests/src/specs/quickstart_pipeline.spec.ts

Reverts fabric8io/fabric8-test#419

Revert "fix(test): Fixed error handling"

---

ee_tests/.gitignore
ee_tests/index.ts
ee_tests/package.json

This change makes page object in this module reusable for other modules.

Make reusable module

---

ee_tests/src/specs/page_objects/main_dashboard.page.ts
ee_tests/src/specs/page_objects/user_profile.page.ts
ee_tests/src/specs/quickstart_che.spec.ts
ee_tests/src/specs/support/quickstart.ts

Updated element locator for current space in recent itemslist, commented out env reset code that encountered inconsistent results, updated analytics results
Minor changes to correct failing tests.

fix(test): Updated element locator for current space in recent items

---

ee_tests/src/specs/page_objects/user_profile.page.ts
ee_tests/src/specs/quickstart_che.spec.ts

Reverts fabric8io/fabric8-test#454

Revert "fix(test): add log statement to debug failures on cluster2"

---

ee_tests/src/specs/page_objects/login.page.ts
ee_tests/src/specs/page_objects/space_cheworkspace.page.ts

Reverts fabric8io/fabric8-test#457

Revert "fix(test) add screenshot of login screen"

---

ee_tests/src/specs/page_objects/space_cheworkspace.page.ts
ee_tests/src/specs/quickstart_pipeline.spec.ts

Reverts fabric8io/fabric8-test#459

Revert "fix(test): look for username length at login"

---

ee_tests/package.json

some clenup will be necessary in other files
resolves #481

fix(test) Chrome driver version is no longer hard-coded

---

ee_tests/cico_run_EE_tests_ts.sh

Changed rsync command so that the files will be stored into the separate
directory for each build.

Changed rsync to store files into directory

---

ee_tests/src/local/local.template.ts
ee_tests/src/page_objects/space_deployments.page.ts
ee_tests/src/quickstart_deployments.spec.ts
ee_tests/src/support/core.ts

This is a proposal of how it might look like if we refactored the code to use object models.

Refactoring of Deployments page

---

ee_tests/src/support/quickstart.ts

Change is required to be in synch with switch to RH maven artifacts

fix(test): update analytics tests to match RH maven changes

---

ee_tests/src/interactions/deployments_interactions.ts
ee_tests/src/interactions/pipelines_interactions.ts
ee_tests/src/quickstart_deployments.spec.ts
ee_tests/src/support/release_strategy.ts

Extracted testing code to separate class - this allows to create various
testing strategies for different release strategies.

Extracted testing code to separate class.

---

ee_tests/ts-protractor.sh

Fixes PR https://github.com/fabric8io/fabric8-test/pull/562

(fix) ee_tests: Make GITHUB_PASSWORD optional 

---

ee_tests/ts-protractor.sh

Fixes PR https://github.com/fabric8io/fabric8-test/pull/562

(fix) ee_tests: Set default value for NGX_LAUNCHER_ENABLED 

---

ee_tests/src/quickstart_deployments.spec.ts

Merged che and dashboard tests into smoketest

---

ee_tests/src/booster_ee_int_tests/booster_che_preview.spec.ts
ee_tests/src/booster_ee_int_tests/booster_modify_src.spec.ts
ee_tests/src/page_objects/space_cheworkspace.page.ts
ee_tests/src/support/core.ts

Multiple changes to bring the tests and page objects in synch with Che6.

fix(test): updated the che-related booster tests for Che6

---

ee_tests/src/interactions/deployments_interactions.ts
ee_tests/src/interactions/pipelines_interactions.ts
ee_tests/src/page_objects/base.page.ts
ee_tests/src/page_objects/main_dashboard.page.ts
ee_tests/src/page_objects/space_dashboard.page.ts
ee_tests/src/page_objects/space_deployments.page.ts
ee_tests/src/page_objects/space_pipeline.page.ts
ee_tests/src/quickstart_deployments.spec.ts
ee_tests/src/support/core.ts

Rewritten opening of some pages + waiting for che window to open.

Removed sleep statements from smoketest (resolves #278).

---

ee_tests/cico_run_EE_tests_ts.sh
ee_tests/config/local_osio.conf.sh.template
ee_tests/entrypoint.sh
ee_tests/local_cico_run_ee_tests.sh
ee_tests/src/quickstart_deployments.spec.ts
ee_tests/src/support/feature_level.ts
ee_tests/ts-protractor.sh

This property will enable to tests OSIO with different feature levels.

Added new property FEATURE_LEVEL

---

ee_tests/src/page_objects/user_profile.page.ts
ee_tests/src/quickstart_deployments.spec.ts

Pull request created on the basis of these two pull requests by @ldimaggi 
https://github.com/fabric8io/fabric8-test/pull/636
https://github.com/fabric8io/fabric8-test/pull/641

Add reset of environment to the beginning of smoke

---

ee_tests/src/interactions/account_home_interactions.ts
ee_tests/src/interactions/deployments_interactions.ts
ee_tests/src/interactions/space_dashboard_interactions.ts
ee_tests/src/page_objects/main_dashboard.page.ts
ee_tests/src/page_objects/space_dashboard.page.ts
ee_tests/src/page_objects/space_dashboard/add_to_space_dialog.ts

PR based on the work of @ldimaggi in PR https://github.com/fabric8io/fabric8-test/pull/642

Added testing of new launcher to smoke beta

---

ee_tests/src/quickstart_analytic.spec.ts
ee_tests/src/quickstart_che.spec.ts

These 2 tests are legacy tests and will eventually be replaced by test cases in the smoke test suite. 
Until that time, they will continue to be run. The updates in this pull request update the tests to support the feature level interactions implemented in the smoke test suite.

fix(test): update the legacy che and analytics tests with interactions

---

EE_API_automation/pytest/src/support/constants.py
EE_API_automation/pytest/src/support/helpers.py
EE_API_automation/pytest/src/support/planner_jsons/create_space.json
EE_API_automation/pytest/src/support/planner_jsons/create_space_scrum.json
EE_API_automation/pytest/src/support/planner_jsons/create_space_sdd.json
EE_API_automation/pytest/src/support/planner_jsons/create_wi_in_backlog_scrum.json
EE_API_automation/pytest/src/support/planner_jsons/create_wi_in_iter_scrum.json
EE_API_automation/pytest/src/test_planner.py
ee_tests/src/interactions/account_home_interactions.ts
ee_tests/src/interactions/deployments_interactions.ts
ee_tests/src/interactions/space_dashboard_interactions.ts
ee_tests/src/page_objects/main_dashboard.page.ts
ee_tests/src/page_objects/space_dashboard.page.ts
ee_tests/src/page_objects/space_dashboard/add_to_space_dialog.ts
ee_tests/src/page_objects/user_profile.page.ts
ee_tests/src/quickstart_analytic.spec.ts
ee_tests/src/quickstart_che.spec.ts

fix(test):add_scrum_template

---

ee_tests/src/booster_ee_int_tests/booster_debug_project.spec.ts
ee_tests/src/booster_ee_int_tests/booster_setup.spec.ts
ee_tests/src/page_objects/space_cheworkspace.page.ts

These changes enable the tests to be run on specified product releases by leveraging the "interactions" interfaces.

fix(test): update booster tests to match ee test framework interactions

---

ee_tests/src/booster_ee_int_tests/booster_analytics_report.spec.ts
ee_tests/src/booster_ee_int_tests/booster_che_preview.spec.ts
ee_tests/src/booster_ee_int_tests/booster_debug_project.spec.ts
ee_tests/src/booster_ee_int_tests/booster_junit_tests.spec.ts
ee_tests/src/booster_ee_int_tests/booster_modify_src.spec.ts
ee_tests/src/support/core.ts

Moved common code into support functions - results in more maintainable and shorter test programs.

fix(test) refactor booster tests that interact with Che

---

ee_tests/README.md
ee_tests/package.json

Reverts fabric8io/fabric8-test#690

Revert "fix(test): added references to the booster tests for the booster team…"

---

ee_tests/Dockerfile.builder
ee_tests/oc-get-jenkins-logs.sh
ee_tests/src/interactions/pipelines_interactions.ts
ee_tests/src/support/core.ts

The logs are retrieved and stored into target/screenshots. In the
future, we may to store them only for failed pipelines.

Added retrieving oc logs

---

EE_API_automation/pytest/src/support/helpers.py
EE_API_automation/pytest/src/test_planner.py

fix(test):change space name and add cleanup

---

EE_API_automation/pytest/src/support/helpers.py
EE_API_automation/pytest/src/test_planner.py

The tests now happily accepts an email ID as OSIO user ID.

fix(test):handle email id as OSIO userID

---

ee_tests/package.json
ee_tests/src/booster_ee_int_tests/booster_modify_src.spec.ts
ee_tests/src/booster_ee_int_tests/booster_trigger_cd.spec.ts
ee_tests/src/interactions/deployments_interactions.ts
ee_tests/src/interactions/pipelines_interactions.ts
ee_tests/src/landing_page.spec.ts
ee_tests/src/login.spec.ts
ee_tests/src/page_objects/app.page.ts
ee_tests/src/page_objects/base.page.ts
ee_tests/src/page_objects/landing.page.ts
ee_tests/src/page_objects/space_cheworkspace.page.ts
ee_tests/src/page_objects/space_dashboard.page.ts
ee_tests/src/page_objects/space_dashboard/add_to_space_dialog.ts
ee_tests/src/page_objects/space_pipeline.page.ts
ee_tests/src/page_objects/user_profile.page.ts
ee_tests/src/planner-simple-create.spec.ts
ee_tests/src/support/build_status.ts
ee_tests/src/support/index.ts
ee_tests/src/support/interactions.ts
ee_tests/src/support/release_strategy.ts
ee_tests/src/ui/base.element.ts
ee_tests/src/ui/checkbox.ts
ee_tests/src/ui/dropdown.ts
ee_tests/src/ui/modal_dialog.ts
ee_tests/src/ui/multi_select_list.ts
ee_tests/src/ui/text_input.ts
ee_tests/src/workshop-quickstart.spec.ts
ee_tests/src/workshop-setup.spec.ts

errors "variable xxx used before declaration" will require bigger refactoring therefore not part of this commit

most of lint errors fixed

---

EE_API_automation/pytest/src/support/constants.py
EE_API_automation/pytest/src/support/helpers.py
EE_API_automation/pytest/src/support/planner_jsons/create_space_scrum.json
EE_API_automation/pytest/src/support/planner_jsons/edit_wi_title.json
EE_API_automation/pytest/src/test_gen_testdb.py
EE_API_automation/pytest/src/test_planner.py

Edited the SCRUM template ID to match the new ID in the WIT.

fix(test)changed scrum template id

---

ee_tests/src/interactions/pipelines_interactions.ts

Only minor improvements
* new logs added in `waitToFinishInternal`
* fixed error in `verifyJenkinsLog`
* updated URL to the Jenkins job
* code formatted

E2E: pipeline interactions improvements

---

ee_tests/src/interactions/pipelines_interactions.ts

The reason for this change is that if there is an error in waitToFinishInternal() method it is than swallowed in catch block and never propagated.

E2E: Refactored waitForPipelineToFinish

---

ee_tests/src/support/index.ts
ee_tests/src/support/login_interactions.ts

Moving the file to correct place will be solved in #805 (can't do immediately because of runtime errors)

E2E: login interactions refactored (#506)

---

booster_api/features/src/import_booster.py
booster_api/features/src/poc_oso.py
booster_api/features/src/poc_stage.py
booster_api/features/src/resetEnv.py
booster_api/features/src/space.py
booster_api/features/src/support/constants.py
booster_api/features/src/support/helpers.py
booster_api/features/src/support/loginusers_oauth2.py
booster_api/features/src/support/moduletest.py
booster_api/setup.cfg

Bunch of minor fixes that don't affect program logic found by `pylinter`. @ldimaggi @pmacik could you please reviews these changes? TY in advance.

Fix PEP8-related warnings in Booster API code

---

self_tests/README.md
self_tests/check-PEP8-style.sh
self_tests/check-python-docstyle.sh
self_tests/measure-cyclomatic-complexity.sh
self_tests/measure-maintainability-index.sh

These are scripts that we use in *analytics* team on CI and on https://fabric8-analytics.github.io/dashboard/dashboard.html as well.
The aim is to have *perfect* code in terms of basic metrics and PEP-standards (so we can show the code to our devops and teach them how to do things properly :). ATM the scripts just check Python code, but we could have something similar for TypeScript in the future (I'm not expert in TS and its tooling though).
Please note, that almost all checks fail at this moment. I'll try to fix most issues (in tests) soon.

Scripts to check python code quality

---

EE_API_automation/pytest/src/test_planner.py

fix(test):space delete issue addressed

---

booster_bdd/features/src/support/constants.py
booster_bdd/features/src/support/helpers.py
booster_bdd/features/src/support/loginusers_oauth2.py

A bunch of minor improvements to make Pylinter happy ;)

Fix Pylint warings in src support directory

---

booster_bdd/check-PEP8-style.sh
booster_bdd/config/config.sh
booster_bdd/run.sh

Fixed issues found by ShellCheck
https://www.shellcheck.net/

Prevent all BASH-related issues

---

booster_bdd/config/config.sh
booster_bdd/config/prod-preview.sh

Before extracting github secrets.

booster-bdd: Make sure you are on the main OSO project 

---

booster_bdd/features/src/support/helpers.py

Minor enhancement - use print() function instead of print statement

Use Python 3-style print function instead of print statement (minor)

---

booster_bdd/.gitignore
booster_bdd/config/config.sh
booster_bdd/config/prod-preview.sh
booster_bdd/local_cico_run_booster_tests.sh
booster_bdd/run.sh

... So the results can be picked up by the jenkins job when running in the docker.

booster-bdd: Make sure the allure results end up in target directory

---

ee_tests/src/booster_ee_int_tests/booster_analytics_report.spec.ts
ee_tests/src/booster_ee_int_tests/booster_cleanup.spec.ts
ee_tests/src/booster_ee_int_tests/booster_import_to_space.spec.ts
ee_tests/src/booster_ee_int_tests/booster_setup.spec.ts
ee_tests/src/interactions/account_home_interactions.ts
ee_tests/src/interactions/codebases_interactions.ts
ee_tests/src/interactions/deployments_interactions.ts
ee_tests/src/interactions/login_interactions.ts
ee_tests/src/interactions/pipelines_interactions.ts
ee_tests/src/interactions/space_dashboard_interactions.ts
ee_tests/src/page_objects/space_codebases.page.ts
ee_tests/src/smoke.spec.ts

Fixes https://github.com/fabric8io/fabric8-test/issues/879

E2E: The interactions naming unified.

---

ee_tests/Dockerfile.builder

See this https://github.com/SatelliteQE/automation-tools/issues/296 for an example of how the output changes when you use `-d1` on `yum install`.

Get rid of progress bars when yum installs

---

booster_bdd/README.md
booster_bdd/features/src/importBooster.py

Users who are running/debugging the tests are encountering request failures and the corresponding response is not being displayed. Also - additional text in the README was needed.

fix(test): uncomment commented out print statement for response

---

EE_API_automation/pytest/src/Dockerfile

Turned ON silent flag for yum and pip install

fix(test): reduced logging

---

EE_API_automation/cico_run_EE_tests.sh

This PR fixes the script to run API tests on prod and prod-preview

fix script to run API tests on prod-preview

---

EE_API_automation/cico_run_EE_tests.sh

Added python-devel dependency to overcome install time failures.

fix failing tests

---

EE_API_automation/pytest/run_me.sh
EE_API_automation/pytest/src/support/constants.py
EE_API_automation/pytest/src/support/helpers.py
EE_API_automation/pytest/src/support/planner_jsons/add_wi_labels.json
EE_API_automation/pytest/src/support/planner_jsons/edit_wi_assignee.json
EE_API_automation/pytest/src/support/planner_jsons/edit_wi_state.json
EE_API_automation/pytest/src/test_planner.py

The tests now can run on WIT running on localhost

fix(test):modify tests to support local runs

---

EE_API_automation/cico_run_EE_tests.sh

Added gcc to the dependency list

fix failing API tests

---

ee_tests/protractor.config.ts
ee_tests/src/interactions/pipelines_interactions.ts
ee_tests/src/interactions/space_dashboard_interactions.ts
ee_tests/src/page_objects/app.page.ts
ee_tests/src/page_objects/main_dashboard.page.ts
ee_tests/src/page_objects/space_codebases.page.ts
ee_tests/src/page_objects/space_dashboard.page.ts
ee_tests/src/page_objects/space_deployments_tab.page.ts
ee_tests/src/page_objects/space_pipeline_tab.page.ts
ee_tests/src/page_objects/user_profile.page.ts
ee_tests/src/page_objects/user_settings.page.ts
ee_tests/src/support/core.ts

+ added description to most of the browser.wait calls

E2E: Set default timeout for browser.wait

---

EE_API_automation/cico_run_EE_tests_wit.sh

- add wit test runner
- add gcc dependency

fix(test):add wit test runner

---

booster_bdd/features/src/support/helpers.py

...to `<username>-BDD-<MM><DD>-<HH><mm>`
Example: `osio-ci-ee9-BDD-0817-1202`

booster-bdd: Shorten the generated space name

---

booster_bdd/config/config.sh
booster_bdd/config/prod-preview.sh

By getting the default value from OSIO user's meta-data.

booster-bdd: Make OSO_CLUSTER_ADDRESS optional

---

ee_tests/clean_test_repos.sh

now it can be used in Jenkins job
simplest local use - will delete up to 30 repos with substring 'e2e' in their name older than 1 week, requires user input
```bash
./clean_test_repos.sh $GITHUB_TOKEN
```
intended Jenkins use - e2e tests create about 120 repos per day, this job should run at least 5 times a day (i.e. it will try to remove up to 150 repos a day)
```bash
yes | ./clean_test_repos.sh $GITHUB_TOKEN
```

e2e: cleanup script improved

---

ee_tests/clean_test_repos.sh

it is necessary for Jenkins job, otherwise we would leak token

e2e: token removed from parameters of cleanup script

---

ee_tests/cico_build_deploy.sh

e2e: devshift variables listed explicitly

---

ee_tests/src/interactions/che_interactions.ts
ee_tests/src/interactions/pipelines_interactions.ts
ee_tests/src/support/script_runner.ts

this is necessary before we add new `oc` commands to `oc-get-jenkins-logs.sh`

e2e: new parameter added to script runner (related to #985)

---

ee_tests/oc-get-jenkins-logs.sh

requested in https://github.com/openshiftio/openshift.io/issues/4215

e2e: Jenkins deployment config info retrieved in oc-get-jenkins-logs.sh

---

ee_tests/src/page_objects/space_dashboard.page.ts

related to https://github.com/openshiftio/openshift.io/issues/3744

e2e: updated logic for analytics report verification

---

ee_tests/src/booster_ee_int_tests/quickstart_che_editor.spec.ts
ee_tests/src/booster_ee_int_tests/quickstart_chejunit.spec.ts
ee_tests/src/booster_ee_int_tests/quickstart_cheterminal.spec.ts
ee_tests/src/booster_pipeline.spec.ts
ee_tests/src/che_integration.spec.ts
ee_tests/src/interactions/pipelines_interactions.ts
ee_tests/src/interactions/space_dashboard_interactions.ts
ee_tests/src/launcher.spec.ts
ee_tests/src/login.spec.ts
ee_tests/src/smoke.spec.ts
ee_tests/src/support/core.ts
ee_tests/src/support/script_runner.ts
ee_tests/src/support/zabbix_reporter.ts

depends on #1051
IMHO it's sufficient to just handle creating directories in 4 places (+ scripts which need to be handled from outside of tests)

e2e: always create directory when saving files

---

ee_tests/src/interactions/che_interactions.ts
ee_tests/src/page_objects/app.page.ts
ee_tests/src/page_objects/space_dashboard.page.ts
ee_tests/src/page_objects/space_dashboard/add_to_space_dialog.ts

space_cheworkspace.ts would be fixed in separate commit (alongside its refactoring)

E2E: Removed tslint:disable commands

---

ee_tests/cico_run_e2e_tests.sh

WARNING merging this PR could break existing Jenkins jobs (logintest, smoketest, PR checks)

e2e: cico_run_e2e_tests.sh refactored and improved to enable PR checks for repo fabric8-ui

---

ee_tests/oc-get-project-logs.sh

Will help debugging https://github.com/openshiftio/openshift.io/issues/3744

e2e: print analysis URL in oc-get-project-logs.sh

---

ee_tests/cico_run_e2e_tests.sh

related to https://github.com/openshiftio/openshiftio-cico-jobs/pull/885

e2e: exit instead of return inside of start_fabric8_ui function

---

ee_tests/config/local_osio.conf.sh.template
ee_tests/src/che_integration.spec.ts
ee_tests/src/interactions/account_home_interactions.ts
ee_tests/src/page_objects/app.page.ts
ee_tests/src/smoke.spec.ts

now it always runs Vert.x http

e2e: tests fixed to run correct quickstart

---

contract_tests/go/auth-api/support/docker-compose.auth.yml
contract_tests/go/auth-api/support/docker-compose.pact-broker.yml
contract_tests/go/auth-api/support/start-local-auth.sh
contract_tests/go/auth-api/support/start-local-pact-broker.sh

Reverts fabric8io/fabric8-test#1163

Revert "Revert "contract-tests: Use docker-compose to start local auth service.""

---

ee_tests/config/local_osio.conf.sh.template
ee_tests/protractor.config.ts
ee_tests/src/interactions/account_home_interactions.ts
ee_tests/src/interactions/launcher_interactions.ts
ee_tests/src/launcher-import.spec.ts
ee_tests/src/page_objects/app.page.ts
ee_tests/src/page_objects/launcher.page.ts
ee_tests/src/support/spec_context.ts

This PR adds tests for import flow of launcher.

launcher test suite for import flow

---

ee_tests/src/interactions/launcher_interactions.ts
ee_tests/src/page_objects/launcher.page.ts

Issue : https://github.com/fabric8io/fabric8-test/issues/1186

Summary page

---

booster_bdd/README.md

Looks like the following:
| | Vert.x | Spring Boot | Thorntail | Node.js | Go |
| :------------- | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: |
| REST HTTP | [![Build Status](https://ci.centos.org/buildStatus/icon?job=devtools-bdd-test-booster-openshift.io-us-east-2a-rest-http-vert.x)](https://ci.centos.org/view/Devtools/job/devtools-bdd-test-booster-openshift.io-us-east-2a-rest-http-vert.x/) | [![Build Status](https://ci.centos.org/buildStatus/icon?job=devtools-bdd-test-booster-openshift.io-us-east-2a-rest-http-spring-boot)](https://ci.centos.org/view/Devtools/job/devtools-bdd-test-booster-openshift.io-us-east-2a-rest-http-spring-boot/) | [![Build Status](https://ci.centos.org/buildStatus/icon?job=devtools-bdd-test-booster-openshift.io-us-east- …

booster-bdd: Update Build Status in README.md to the form of a matrix.

---

ee_tests/src/support/screenshot_manager.ts

How to test:
1. add something like this anywhere in your test
```
// tslint:disable:max-line-length
browser.executeScript('console.error("WebSocket connection to \'wss://openshiftapps.com/pty?token=eyasdfasdfasdfasdfI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlYTFhb3N5OHh1MWMyajF4dyJ9.eyJ3c2lkIjoid29ya3NwYWNlYTFhb3N5OHh1MWMyajF4dyIsInVpZCI6IjQ4NDY1NTRhLWQyYmMtNGY0Mi04N2Q5LTg1MzdhM2YzMzZlOCIsImF1ZCI6IndvcmtzcGFjZWExYW9zeTh4dTFjMmoxeHciLCJuYmYiOi0xLCJ1bmFtZSI6Im9zaW8tY2ktZTJlLTAwMy1wcmV2aWV3IiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE1Nzk4Nzc0NTMsImlhdCI6MTU0ODM0MTQ1MywianRpIjoiNjMxY2RiODYtZWI0OS00YWRhLWFhMTYtODQwMDg2ODkzOTRkIn0.iwqR9X0_S7MLAztd16ewJ5PBDKzJTp4trUCw4vTlmNFFKuTf96KZnDHSGCKgYXaLOnR-iSLjiTykWrUsolLwsjuZHd5_FLhgQ8ZAPnhEkdzy03eHk9HYX7T5Um9fKZfyNCkaon51HEybEEJJDqHzmiBv8fH-lolB3 …
```

e2e: hide JWT tokens in URL parameters
