- ee_tests/cico_run_EE_tests.sh
In the jenkins job, we have to move one level down inside the payload directory which might contain the jenkins-env file. https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml#L865
> ee_test: Search for jenkins-env in the parent directory

- ee_tests/cico_run_EE_tests.sh
`ARTIFACT_PASS` is not a credential, so Jenkins will not obfuscate it and as it should be kept secret, we cannot allow to use `set -x`.
Also the variable has been incorrectly names in the docker run command.
> Fix ARTIFACT_PASS name and prevent it from being displayed

- EE_API_automation/pyresttest/Dockerfile
This is a fixup for #102.
In order to avoid to having to modify paths in YAML files (e.g. `- import:  get_a_space.yaml`) we default to the `/tests` working directory where you should volume mount your tests.
Now you can use the `Dockerfile` like so:
```
$ cd EE_API_automation/pyresttest
$ docker build -t ee . -f Dockerfile
$ docker run --rm -it -v $PWD:/tests:ro ee https://api.openshift.io API_automation_workshop.yaml --vars="{'token':'YOUR_TOKEN', 'userid':'USERNAME'}" --interactive true
```
> default to /tests as the working directory

- ee_tests/common.inc.sh
- ee_tests/local_run_EE_tests.sh
- ee_tests/ts-protractor.sh
This patch refactors the common code used in ts-protractor.sh and
local_run_EE_tests.sh to common.inc.sh.
The ts-protractor.sh now starts the webdriver if it isn't running
already and runs tsc to compile typescript to js before running
the tests.
> Share common validation and webdriver functions

- ee_tests/local_run_EE_tests.sh
The script crashed when it evaluation [[ $CAT_LOGFILE == 'true' ]]
and CAT_LOGFILE wasn't defined. Since CAT_LOGFILE is optional, this
patch fixes it by setting the default to 'false'
> local_run_EE_test: fix crash when CAT_LOGFILE is undefined

- ee_tests/README.md
- ee_tests/package-lock.json
- ee_tests/package.json
- ee_tests/yarn.lock
Fixes package.json to:
- downgrade typescript version to 2.5.3 (OSIO currently uses 2.5.3)
- postinstall: now updates webdriver since is a mandatory step
after running yarn
- split devDependencies to actual devDependencies and dependencies
based on the packages needed to run e2e
Adds package-lock.json along with yarn.lock so that packages are pinned
down when installing using npm (> 5)
README.md has been updated to reflect these changes.
> Fix npm package versions and scripts

- ee_tests/src/specs/page_objects/main_dashboard.page.ts
The time taken for the main-dashboard page to load seems to have
increased. This patch waits for the 'getting started' page to
change (by waiting for the url to change) before checking if the
header and navigation bar are present.
(cherry picked from commit 4d3b5b778621aed8061c8c5b6065aa7f6f315f6d)
> MainDashboard: wait for the page url to change

- EE_API_automation/pytest/json2env
How to use - `eval $(cat file.json | ./json2env)`
> fix(pytest): Add json2env script which converts JSON file to env variables

- ee_tests/src/specs/booster_pipeline.spec.ts
- ee_tests/src/specs/quickstart_analytic.spec.ts
- ee_tests/src/specs/quickstart_che.spec.ts
- ee_tests/src/specs/quickstart_deployments.spec.ts
- ee_tests/src/specs/quickstart_pipeline.spec.ts
- ee_tests/src/specs/support/quickstart.ts
Quickstart selection refactored so that now all quickstarts are defined in one place.
tested with these configurations:
runTest / vertxHttp / releaseStageApproveAndPromote
quickstartTest / vertxHttp / releaseStageApproveAndPromote
chequickstartTest / vertxHttp / releaseStageApproveAndPromote
runTest / vertxHttp / release
runTest / vertxHealth / releaseStageApproveAndPromote
runTest / SpringBootHttp / releaseAndStage
runTest / SpringBootHealth / releaseStageApproveAndPromote
runTest / SwarmHttp / releaseStageApproveAndPromote
runTest / SwarmHealth / releaseStageApproveAndPromote
> refactor(test): quickstart selection refactored

- ee_tests/src/specs/page_objects/login.page.ts
We are seeing login failures for an automated test that utilizes a user account on the new cluster. The username/password credential has been reset, but the test is still failing. This change dumps all login page text to stdout to enable us to debug the failures. The change intentionally takes ALL the text from the page and not only any error message/alert. The username/password are not printed to stdout.
> fix(test): dump all text from login page to stdout - to aid in debugging

- ee_tests/protractorTS.config.ts
- ee_tests/src/specs/page_objects/login.page.ts
- ee_tests/src/specs/page_objects/space_cheworkspace.page.ts
- ee_tests/src/specs/quickstart_cheterminal.spec.ts
- ee_tests/src/specs/support/core.ts
This test verifies the operation of running maven install and test commands within a quickstart/booster's Che workspace terminal window. This test is one of the required tetss defined for boosters.
> fix(test): Initial test for executing test from mvn in Che workspace terminal shell

- ee_tests/src/support/quickstart.ts
This fix will enable the E2E test running on Centos Ci to pass. The other tests will be addressed in other pull requests.
> fix(test): correct error in analytics report values

- ee_tests/protractorTS.config.ts
- ee_tests/src/page_objects/space_cheworkspace.page.ts
- ee_tests/src/quickstart_chejunit.spec.ts
- ee_tests/src/support/core.ts
This is a sample test, illustrating running a maven build in the Che terminal window, and then running Junit tests in Che. We will likely refactor this test into a booster test by extracting much of the test setup into separate tests in a test suite.
> fix(test): poc test for junit tests running in Che

- ee_tests/.gitignore
- ee_tests/declarations.d.ts
- ee_tests/package-lock.json
- ee_tests/package.json
- ee_tests/protractorTS.config.ts
Added protractor-fail-fast dependency that allows to exit tests  on the first failure
instead of running all tests.
> Added protractor-fail-fast

- ee_tests/src/support/quickstart.ts
This is an odd one - as the order was also changed a couple of weeks ago. Will investigate with the analytics team.
> fix(test): The reports fields shifted - causing test failures

- ee_tests/cico_run_EE_tests_ts.sh
Previous attempt was not completely successful - it created the right
structure but did not copy the files.
> Changed rsync to store files into directory

- ee_tests/src/page_objects/space_deployments.page.ts
The smoketest is repeatedly failing on Centos CI - due to the deployments' page applications not being found. In debugging/running this locally, I found that it was happening intermittently. Must be a timing issue. 
```
Creating new quickstart in OSIO Create a new space, new vertxHttp quickstart, run its pipeline
- Expected 0 to be 1, 'number of deployed applications'.
- Failed: Cannot read property 'getName' of undefined
```
Adding protractor expected condition (until) to wait until the applications are visible. This passed 10 of 10 attempts running locally. Without this change - the test failed 2 out of 10 times locally.
> fix(test): add browser wait statements to ensure that UI elements are present

- ee_tests/protractorTS.config.ts
- ee_tests/src/booster_ee_int_tests/booster_che_preview.spec.ts
- ee_tests/src/booster_ee_int_tests/quickstart_che_editor.spec.ts
- ee_tests/src/page_objects/booster_endpoint.page.ts
- ee_tests/src/page_objects/space_che.page.ts
- ee_tests/src/page_objects/space_cheworkspace.page.ts
- ee_tests/src/support/core.ts
- ee_tests/src/support/launcher_runtime.ts
- ee_tests/ts-protractor.sh
New pull request to replace: https://github.com/fabric8io/fabric8-test/pull/558
In this new pull request:
* New test is added to verify a deployed app's endpoint in the Che preview URL
* New test is added to modify an app's source and then verify deployed app's endpoint in the Che preview URL
These tests are running successfully 95%+ of the time when run locally (In Boston). Failures were seen in Brno in running https://github.com/fabric8io/fabric8-test/pull/558 - the theory is that network latency was the cause of these errors. We need to verify with the tests in this new pull request - and also run the tests in other geographic locations to determine if location is a factor.
> fix(test): added booster tests: preview app, modify src file

- ee_tests/src/interactions/pipelines_interactions.ts
As the che test was introduced to run before pipelines test, we cannot
assume that the status of build upon page load is NEW.
> Removed expec for build status (resolved #581)

- ee_tests/Dockerfile.builder
- ee_tests/cico_build_deploy.sh
- ee_tests/cico_run_EE_tests_ts.sh
- ee_tests/docker-entrypoint.sh
- ee_tests/local_cico_run_ee_tests.sh
1. remove ENTRYPOINT in `Dockerfile.builder` so that Chrome version can be obtained safely
2. tag Docker image with not only `latest` but also with Chrome version (e.g. `66.0.3359.117`)
TODO do we need to re-sync source files in case that tests start using tagged version instead of `latest`? Can we postpone this?
> Tagging of docker images

- ee_tests/Dockerfile.builder
- ee_tests/declarations.d.ts
- ee_tests/package-lock.json
- ee_tests/package.json
- ee_tests/protractor.config.ts
The reporter is intended to be used mainly in Docker image. On local
machine, it needs to have ffmpeg installed and might or might not work
well (dependeing on the system configuration).
Use: you need to enable reporter in protractor.config.ts. (set
useVideoReporter=true) and uncomment ffmpeg instalation in
Dockerfile.builder. The video will be stored in target/videos.
> Added video reporter

- ee_tests/src/page_objects/user_settings.page.ts
now it returns e.g. 'released' instead of 'on'
> function getFeatureLevel fixed

- ee_tests/src/page_objects/user_profile.page.ts
In case a second `Reset environment` is needed in the cleanup phase, the username (e.g. `user_name`) remains filled in from the previous attempt so entering it a second time causes it to be invalid (`user_nameuseruser_name`). So I added a line to clean the input box before it is filled with the user name.
> ee_tests: Clear confirmation input before entering username.

- EE_API_automation/pytest/run_me.sh
- EE_API_automation/pytest/src/support/helpers.py
- EE_API_automation/pytest/src/test_gen_testdb.py
This PR adds a new test file, which will be used by Planner EE UI tests to generate minimal test data needed. 
The extensive API tests would only run in standalone mode on CentOS CI periodically.
> feat(test):add minified api tests

- ee_tests/cico_run_e2e_tests.sh
Right now, Jenkins jobs generate `zabbix-report.txt` file containing lines like this:
```
beta.smoketest.login 1527154649079 38.879
```
but expected value is something like this:
```
us-east-1b beta.smoketest.login 1527154649079 38.879
```
Line break in the bash script causes variables not being filtered correctly.
> CICO run script fixed to filter env variables correctly

- ee_tests/README.md
The sections removed are all old and no longer applicable. Let's limit the contents of the README to only current and correct information to assist anyone in running the tests.
> fix(test) remove outdated sections of README

- ee_tests/config/local_osio.conf.sh.template
This sets the default value of `TEST_SUITE` for the config template to a valid value, `all`. A comment is also added so users are informed of where they can look for the list of existing test suites and extra new lines are removed (I guess my IDE did that...)
Thoughts? I'm open to a different default test suite, however as a user, I'd prefer one that's at least valid.
> fix(config): set template default test suite to valid value

- ee_tests/cico_run_e2e_tests.sh
- ee_tests/local_cico_run_e2e_tests.sh
should work with Fedora and CentOS, not tested with Ubuntu
> E2E: run scripts updated to set local timezone in Docker container

- ee_tests/package-lock.json
- ee_tests/package.json
- ee_tests/src/page_objects/base.page.ts
- ee_tests/src/ui/base.element.ts
exclamation mark had to be added to methods `log` and `debug` because TypeScript 2.7+ is much stricter than older versions
> E2E TypeScript upgraded to latest version (#480)

- ee_tests/Dockerfile.builder
- ee_tests/cico_run_e2e_tests.sh
1. `yum install`'s output redirected to a file
2. `yum install`'s execution time printed (for later analysis)
3. `docker pull`'s output redirected to a file
4. `docker pull`'s execution time printed (for later analysis)
5. `rsync` runs from Duffy node directly, not from Docker container
6. `rsync` no longer installed in Dockerfile
7. unnecessary manipulation with `rsync` password file removed
> E2E: archiving artifacts in cico run script improved (resolves #696)

- ee_tests/cico_run_e2e_tests.sh
screenshots and zabbix report are not being uploaded because of this error: `must specify at least one container source`
> E2E: docker cp requires container source

- booster_bdd/features/src/pipeline.py
Sorry @pmacik, I did not catch this issue in yesterday's PM (https://github.com/fabric8io/fabric8-test/pull/853/files), but:
```
except (IndexError, e):
```
is not semantically correct. Well, in fact tuple can be used here, but just for catching multiple exception types, and the syntax is (Python 2.x, Python 3.x):
```
except (Exception1, Exception2) as e:
```
or (Python 2,x, deprecated AFAIK):
```
except (Exception1, Exception2), e:
```
> Fix semantic error in exception handling

- self_tests/README.md
- self_tests/check-bashscripts.sh
This new script can be used to check all BASH scripts for common mistakes, issues, incompatibilities, and caveats.
> Script to check all BASH scripts

- booster_bdd/features/src/pipeline.py
- booster_bdd/features/steps/createSpace.py
- booster_bdd/features/steps/importBooster.py
- booster_bdd/features/steps/loginUser.py
- booster_bdd/features/steps/resetEnvironment.py
- booster_bdd/features/steps/verifyPipeline.py
- booster_bdd/features/steps/verifyRun.py
- booster_bdd/features/steps/verifyStage.py
- booster_bdd/requirements.txt
If Python is started with the -O option (optimizations), the built-in assertions are stripped out and not evaluated.
This replaces the `assert` statements in tests by the `pyshould` library.
> booster-bdd: Use pyshould library instead of asserts.

- ee_tests/src/interactions/codebases_interactions.ts
@ldimaggi @pmacik @rgarg1 @ljelinkova  please review and merge, e2e tests are failing in prod because new behavior of button was promoted from prod-preview to prod
> e2e: create workspace button behavior changed in prod

- ee_tests/cico_build_deploy.sh
Jenkins job https://ci.centos.org/view/Devtools/job/devtools-fabric8-test-build-master/ is broken, this PR fixes that
> e2e: unnecessary variables removed from cico_build_deploy.sh

- ee_tests/src/interactions/pipelines_interactions.ts
there are messages like this in Jenkins log, this PR fixes that:
```
[13:23:32] W/element - more than one element found for locator By(xpath, //h3[text()="Status"]/../dl/dd/span) - the first result will be used
```
> e2e: locator for pipeline status fixed

- ee_tests/local_clean_test_repos.sh
We don't want the Jenkins job fail unnecessarily https://ci.centos.org/view/Devtools/job/devtools-test-e2e-cleanup/315/console
> e2e: do not fail script for cleaning github repos when nothing to delete

- ee_tests/protractor.config.ts
- ee_tests/src/support/failures_reporter.ts
1. it stores report to `target/screenshots`, this will be fixed in some other PR
2. it creates the file in `specDone` instead of `suiteDone` because `suiteDone` doesn't have these data, I guess that it is related to fail fast plugin that we use
> e2e: failures reporter created

- ee_tests/package.json
- ee_tests/protractor.config.ts
- ee_tests/src/page_objects/space_settings.page.ts
- ee_tests/src/page_objects/user_profile.page.ts
- ee_tests/src/planner.spec.ts
This PR adds Integration tests for Planner -
- creating child areas and adding it to a workitem
- Opening Assigned workitem from profile page
- adding collaborator and assigning it a workitem
Planner page object are shared and reused for Integration tests
Planner page objects - https://www.npmjs.com/package/planner-functional-test
The package is published from - https://github.com/fabric8-ui/fabric8-planner/pull/2779
and soon this PR will be merged in planner master.
Areas tests for prod-preview will fail 
open issue- https://github.com/openshiftio/openshift.io/issues/4366
> Planner Integration tests

- ee_tests/src/support/window_manager.ts
> e2e: workaround for pages not loading in new tab

- ee_tests/package.json
After running `npm run image:build` multiple times (always with some change), user ends up with something like this:
```
$ docker images     
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
fabric8-test                   latest              bb561ff9c077        6 hours ago         1.15 GB
<none>                      <none>              28773a37435b        6 hours ago         1.15 GB
<none>                      <none>              a05286f41e49        24 hours ago        1.15 GB
<none>                      <none>              9af360fcf850        26 hours ago        1.14 GB
<none>                      <none>              0574c488674e        47 hours ago        1.14 GB
<none>                      <none>              d76b17b045f4        2 days …
```
> e2e: tagging of local docker images improved

- ee_tests/src/interactions/launcher_interactions.ts
- ee_tests/src/page_objects/launcher.page.ts
1. fixed couple of typos in function names
2. await instead of return, should fix random failures in tests such as https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/3602/console
> e2e: small fixes in launcher page object and interactions

- booster_bdd/features/src/resetEnv.py
Workaround for https://github.com/openshiftio/openshift.io/issues/4559
> booster-bdd: Delete che workspaces for spaces during env reset.

- ee_tests/oc-get-project-logs.sh
Old logs in `./target/screenshots/oc-che-logs.txt`
```
Number of existing workspaces: 45
List of existing workspaces:
{
"workspace_name": "e2e-0121-0037-162-egznb",
"project_name": "e2e-0121-0037-162"
}
{
"workspace_name": "e2e-0120-0237-3764-wba8n",
"project_name": "e2e-0120-0237-3764"
}
...
```
New
```
Number of existing workspaces: 45
List of existing workspaces:
"e2e-0121-0037-162-egznb"
"e2e-0120-0237-3764-wba8n"
...
```
> e2e: log only names of che workspaces, no space names

- ee_tests/src/page_objects/space_codebases.page.ts
Possible fix for https://github.com/openshiftio/openshift.io/issues/4720
The e2e tests try to click on the outer div (green colored) while the achor tag is on the text inside the div (yellow color). With this PR, the e2e tests will click on the yellow text instead of the green div.
> e2e: Change create workspace selector

- self_tests/measure-cyclomatic-complexity.sh
- self_tests/measure-maintainability-index.sh
Let's use the older Radon 2.4.0 instead of 3.0.0. We'll need to wait for fix for the following issue to use 3.0.0:
https://github.com/rubik/radon/issues/166
> Use Radon 2.4.0 instead of 3.0.0
